export const REQUEST_POSTS = "REQUEST_POSTS"
export const SUCCESS_POSTS = "SUCCESS_POSTS"
export const FAIL_POSTS = "FAIL_POSTS"
export const REQUEST_COMMENT = "REQUEST_COMMENT"
export const SEARCH = "SEARCH"
export const PAGINATED_POSTS = "PAGINATED_POSTS"

export const REQUEST_SINGLE_POSTS = "REQUEST_SINGLE_POSTS"
