export const REQUEST_TODO = "REQUEST_TODO"
export const SUCCESS_TODO = "SUCCESS_TODO"
export const SEARCH = "SEARCH"
export const ADD = "ADD"
export const DELETE = "DELETE"
export const STATUS_CHANGED = "STATUS_CHANGED"